window.AV =
  PolarPlot: require('./polar-plot')
  PolarPlotHeatmap: require('./polar-plot-heatmap')
  PolarPlotWaypoints: require('./polar-plot-waypoints')
  HorizontalBarChart: require('./horizontal-bar-chart')
  Audiogram: require('./audiogram')
  MergeablePolarPlots: require('./mergeable-polar-plots')
  HRTF: require('./hrtf')
  SpatialSound: require('./spatial-sound')
